CREATE TABLE Contient
(
	IntituleFormation VARCHAR(50) PRIMARY KEY NOT NULL,
	CodeModule VARCHAR(10) PRIMARY KEY NOT NULL,
  FOREIGN KEY(CodeModule) REFERENCES Module(Code),
  FOREIGN KEY(IntituleFormation) REFERENCES Formation(Intitule)
);

INSERT INTO Contient VALUES('M1 DATASCALE', 'MIN17213');
INSERT INTO Contient VALUES('M1 DATASCALE', 'MIN17214');
INSERT INTO Contient VALUES('M1 AMIS', 'MIN17211');
INSERT INTO Contient VALUES('M1 AMIS', 'MIN17212');
INSERT INTO Contient VALUES('M1 SECRETS', 'MIN17217');
INSERT INTO Contient VALUES('M1 SECRETS', 'MIN17218');
INSERT INTO Contient VALUES('M1 RESEAUX', 'MIN17216');
INSERT INTO Contient VALUES('M1 RESEAUX', 'MIN17215');
