CREATE table Formation
(
	Intitule varchar(50) PRIMARY KEY NOT NULL,
);

INSERT INTO Formation VALUES('M1 DATASCALE');
INSERT INTO Formation VALUES('M1 AMIS');
INSERT INTO Formation VALUES('M1 SECRETS');
INSERT INTO Formation VALUES('M1 RESEAUX');
INSERT INTO Formation VALUES('M2 DATASCALE');
INSERT INTO Formation VALUES('M2 AMIS');
INSERT INTO Formation VALUES('M2 SECRETS');
INSERT INTO Formation VALUES('M2 RESEAUX');
