CREATE table Salle
(
	NomSalle varchar(50) PRIMARY KEY NOT NULL,
	Type Varchar(30),
	Capacite int
);

INSERT INTO Salle VALUES('G001', 'Cours', 30);
INSERT INTO Salle VALUES('G002', 'Cours', 30);
INSERT INTO Salle VALUES('G003', 'Cours', 30);
INSERT INTO Salle VALUES('G004', 'Cours', 30);
INSERT INTO Salle VALUES('G005', 'Cours', 30);
INSERT INTO Salle VALUES('G006', 'Cours', 30);
INSERT INTO Salle VALUES('G007', 'Cours', 30);
INSERT INTO Salle VALUES('G008', 'Cours', 30);
INSERT INTO Salle VALUES('G009', 'Cours', 30);
INSERT INTO Salle VALUES('G101', 'Cours', 30);
INSERT INTO Salle VALUES('G102', 'Cours', 30);
INSERT INTO Salle VALUES('G103', 'Cours', 30);
INSERT INTO Salle VALUES('G104', 'Cours', 30);
INSERT INTO Salle VALUES('G105', 'Cours', 30);
INSERT INTO Salle VALUES('G106', 'Cours', 30);
INSERT INTO Salle VALUES('G107', 'Cours', 30);
INSERT INTO Salle VALUES('G108', 'Cours', 30);
INSERT INTO Salle VALUES('G109', 'Cours', 30);
INSERT INTO Salle VALUES('G201', 'Informatique', 30);
INSERT INTO Salle VALUES('G202', 'Informatique', 30);
INSERT INTO Salle VALUES('G203', 'Informatique', 30);
INSERT INTO Salle VALUES('G204', 'Informatique', 30);
INSERT INTO Salle VALUES('G205', 'Informatique', 30);
INSERT INTO Salle VALUES('G206', 'Informatique', 30);
INSERT INTO Salle VALUES('G207', 'Informatique', 30);
INSERT INTO Salle VALUES('G208', 'Informatique', 30);
INSERT INTO Salle VALUES('G209', 'Informatique', 30);
INSERT INTO Salle VALUES('G210', 'Informatique', 30);
INSERT INTO Salle VALUES('2101', 'Cours', 20);
INSERT INTO Salle VALUES('2102', 'Cours', 20);
INSERT INTO Salle VALUES('2103', 'Cours', 20);
INSERT INTO Salle VALUES('2104', 'Cours', 20);
INSERT INTO Salle VALUES('2105', 'Cours', 20);
INSERT INTO Salle VALUES('2106', 'Cours', 20);
INSERT INTO Salle VALUES('2107', 'Cours', 20);
INSERT INTO Salle VALUES('2108', 'Cours', 20);
INSERT INTO Salle VALUES('2109', 'Cours', 20);
INSERT INTO Salle VALUES('2201', 'Cours', 20);
INSERT INTO Salle VALUES('2202', 'Cours', 20);
INSERT INTO Salle VALUES('2203', 'Cours', 20);
INSERT INTO Salle VALUES('2204', 'Cours', 20);
INSERT INTO Salle VALUES('2205', 'Cours', 20);
INSERT INTO Salle VALUES('Amphi A', 'Amphi', 100);
INSERT INTO Salle VALUES('Amphi B', 'Amphi', 100);
INSERT INTO Salle VALUES('Amphi C', 'Amphi', 100);
INSERT INTO Salle VALUES('Amphi D', 'Amphi', 100);
INSERT INTO Salle VALUES('Amphi E', 'Amphi', 100);
INSERT INTO Salle VALUES('Amphi F', 'Amphi', 100);
INSERT INTO Salle VALUES('Amphi G', 'Amphi', 100);
INSERT INTO Salle VALUES('Amphi H', 'Amphi', 100);
INSERT INTO Salle VALUES('Amphi I', 'Amphi', 100);
INSERT INTO Salle VALUES('Amphi J', 'Amphi', 100);
INSERT INTO Salle VALUES('ALSACE', 'Informatique', 40);
INSERT INTO Salle VALUES('JUNGLE', 'Informatique', 40);
INSERT INTO Salle VALUES('RC20', 'Informatique', 20);
INSERT INTO Salle VALUES('RC21', 'Informatique', 20);
INSERT INTO Salle VALUES('RC22', 'Informatique', 20);
INSERT INTO Salle VALUES('RC23', 'Informatique', 20);
INSERT INTO Salle VALUES('RC24', 'Informatique', 20);
INSERT INTO Salle VALUES('RC25', 'Informatique', 20);
INSERT INTO Salle VALUES('RC26', 'Informatique', 20);
INSERT INTO Salle VALUES('RC27', 'Informatique', 20);
INSERT INTO Salle VALUES('RC28', 'Informatique', 20);
INSERT INTO Salle VALUES('RC29', 'Informatique', 20);
